global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h
  receiver: 'jenkins-rollback-webhook'

receivers:
  - name: 'jenkins-rollback-webhook'
    webhook_configs:
      - url: 'http://98.82.242.170:8080/generic-webhook-trigger/invoke?token=ROLLBACK_256094_TOKEN'
        http_config:
          basic_auth:
            username: 'ashtarali4'
            password: '1149bc007ee3691a20b5045b081b823cba'
        send_resolved: false

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname']
